# Generated by Django 4.2.5 on 2023-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('valorUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cantidadProducto', models.IntegerField(max_length=10)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbInventario',
            },
        ),
    ]
